// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: types_v1.proto

package core_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	COREService_CreateEntity_FullMethodName = "/core.COREService/CreateEntity"
	COREService_ReadEntity_FullMethodName   = "/core.COREService/ReadEntity"
	COREService_ReadEntities_FullMethodName = "/core.COREService/ReadEntities"
	COREService_UpdateEntity_FullMethodName = "/core.COREService/UpdateEntity"
	COREService_DeleteEntity_FullMethodName = "/core.COREService/DeleteEntity"
)

// COREServiceClient is the client API for COREService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for CORE operations
type COREServiceClient interface {
	CreateEntity(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Entity, error)
	ReadEntity(ctx context.Context, in *ReadEntityRequest, opts ...grpc.CallOption) (*Entity, error)
	ReadEntities(ctx context.Context, in *ReadEntityRequest, opts ...grpc.CallOption) (*EntityList, error)
	UpdateEntity(ctx context.Context, in *UpdateEntityRequest, opts ...grpc.CallOption) (*Entity, error)
	DeleteEntity(ctx context.Context, in *EntityId, opts ...grpc.CallOption) (*Empty, error)
}

type cOREServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCOREServiceClient(cc grpc.ClientConnInterface) COREServiceClient {
	return &cOREServiceClient{cc}
}

func (c *cOREServiceClient) CreateEntity(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Entity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Entity)
	err := c.cc.Invoke(ctx, COREService_CreateEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cOREServiceClient) ReadEntity(ctx context.Context, in *ReadEntityRequest, opts ...grpc.CallOption) (*Entity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Entity)
	err := c.cc.Invoke(ctx, COREService_ReadEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cOREServiceClient) ReadEntities(ctx context.Context, in *ReadEntityRequest, opts ...grpc.CallOption) (*EntityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityList)
	err := c.cc.Invoke(ctx, COREService_ReadEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cOREServiceClient) UpdateEntity(ctx context.Context, in *UpdateEntityRequest, opts ...grpc.CallOption) (*Entity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Entity)
	err := c.cc.Invoke(ctx, COREService_UpdateEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cOREServiceClient) DeleteEntity(ctx context.Context, in *EntityId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, COREService_DeleteEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// COREServiceServer is the server API for COREService service.
// All implementations must embed UnimplementedCOREServiceServer
// for forward compatibility.
//
// Service definition for CORE operations
type COREServiceServer interface {
	CreateEntity(context.Context, *Entity) (*Entity, error)
	ReadEntity(context.Context, *ReadEntityRequest) (*Entity, error)
	ReadEntities(context.Context, *ReadEntityRequest) (*EntityList, error)
	UpdateEntity(context.Context, *UpdateEntityRequest) (*Entity, error)
	DeleteEntity(context.Context, *EntityId) (*Empty, error)
	mustEmbedUnimplementedCOREServiceServer()
}

// UnimplementedCOREServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCOREServiceServer struct{}

func (UnimplementedCOREServiceServer) CreateEntity(context.Context, *Entity) (*Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntity not implemented")
}
func (UnimplementedCOREServiceServer) ReadEntity(context.Context, *ReadEntityRequest) (*Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadEntity not implemented")
}
func (UnimplementedCOREServiceServer) ReadEntities(context.Context, *ReadEntityRequest) (*EntityList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadEntities not implemented")
}
func (UnimplementedCOREServiceServer) UpdateEntity(context.Context, *UpdateEntityRequest) (*Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEntity not implemented")
}
func (UnimplementedCOREServiceServer) DeleteEntity(context.Context, *EntityId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntity not implemented")
}
func (UnimplementedCOREServiceServer) mustEmbedUnimplementedCOREServiceServer() {}
func (UnimplementedCOREServiceServer) testEmbeddedByValue()                     {}

// UnsafeCOREServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to COREServiceServer will
// result in compilation errors.
type UnsafeCOREServiceServer interface {
	mustEmbedUnimplementedCOREServiceServer()
}

func RegisterCOREServiceServer(s grpc.ServiceRegistrar, srv COREServiceServer) {
	// If the following call pancis, it indicates UnimplementedCOREServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&COREService_ServiceDesc, srv)
}

func _COREService_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(COREServiceServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: COREService_CreateEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(COREServiceServer).CreateEntity(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _COREService_ReadEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(COREServiceServer).ReadEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: COREService_ReadEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(COREServiceServer).ReadEntity(ctx, req.(*ReadEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _COREService_ReadEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(COREServiceServer).ReadEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: COREService_ReadEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(COREServiceServer).ReadEntities(ctx, req.(*ReadEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _COREService_UpdateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(COREServiceServer).UpdateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: COREService_UpdateEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(COREServiceServer).UpdateEntity(ctx, req.(*UpdateEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _COREService_DeleteEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(COREServiceServer).DeleteEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: COREService_DeleteEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(COREServiceServer).DeleteEntity(ctx, req.(*EntityId))
	}
	return interceptor(ctx, in, info, handler)
}

// COREService_ServiceDesc is the grpc.ServiceDesc for COREService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var COREService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.COREService",
	HandlerType: (*COREServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntity",
			Handler:    _COREService_CreateEntity_Handler,
		},
		{
			MethodName: "ReadEntity",
			Handler:    _COREService_ReadEntity_Handler,
		},
		{
			MethodName: "ReadEntities",
			Handler:    _COREService_ReadEntities_Handler,
		},
		{
			MethodName: "UpdateEntity",
			Handler:    _COREService_UpdateEntity_Handler,
		},
		{
			MethodName: "DeleteEntity",
			Handler:    _COREService_DeleteEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types_v1.proto",
}
